[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"


[[plugins]]
  # runs Cypress tests against the deployed URL
  package = "netlify-plugin-cypress"
  